// packages/vue/src/components/AuthorInfo.vue
<template>
	<span class="discord-author-info">
		<span class="discord-author-username" :style="{ color: roleColor }">
			{{ author }}
		</span>
		<span v-if="bot" class="discord-author-bot-tag">
			Bot
		</span>
	</span>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
	name: 'AuthorInfo',
	props: {
		author: String,
		bot: Boolean,
		roleColor: String,
	},
})
</script>

<style src="@discord-message-components/core/dist/styles/discord-author-info.css"></style>

// packages/react/src/components/AuthorInfo.tsx
import React, { ReactElement } from 'react'
import '@discord-message-components/core/dist/styles/discord-author-info.css'

type AuthorInfoProps = {
	author?: string,
	bot?: boolean,
	roleColor?: string,
}

export default function AuthorInfo({ author, bot, roleColor }: AuthorInfoProps): ReactElement {
	return (
		<span className="discord-author-info">
			<span style={{ color: roleColor }} className="discord-author-username">
				{author}
			</span>
			{bot
				&& <span className="discord-author-bot-tag">
					Bot
				</span>}
		</span>
	)
}
