// packages/vue/src/components/DiscordMessages.vue
<template>
	<div class="discord-messages" :class="{ 'discord-compact-mode': compactMode, 'discord-light-theme': lightTheme }">
		<slot></slot>
	</div>
</template>

<script lang="ts">
import { defineComponent, provide } from 'vue'

export default defineComponent({
	name: 'DiscordMessages',
	props: {
		compactMode: Boolean,
		lightTheme: Boolean,
	},
	setup(props) {
		provide('compactMode', props.compactMode)
	},
})
</script>

<style src="@discord-message-components/core/dist/styles/discord-messages.css"></style>

// packages/react/src/components/DiscordMessages.tsx
import React, { Children, cloneElement, PropsWithChildren, ReactElement } from 'react'
import '@discord-message-components/core/dist/styles/discord-messages.css'

export type DiscordMessagesProps = PropsWithChildren<{
	compactMode?: boolean,
	lightTheme?: boolean,
}>

export default function DiscordMessages({ children, compactMode, lightTheme }: DiscordMessagesProps): ReactElement {
	let classes = 'discord-messages'
	if (lightTheme) classes += ' discord-light-theme'
	if (compactMode) classes += ' discord-compact-mode'

	const messages = Children.map((children as ReactElement[]), (child: ReactElement, index: number): ReactElement => {
		return cloneElement(child, { compactMode, key: index })
	})

	return (
		<div className={classes}>
			{messages}
		</div>
	)
}
