// packages/vue/src/components/DiscordEmbedField.vue
<template>
	<div :class="{ 'discord-embed-field-inline': inline }" class="discord-embed-field">
		<div class="discord-embed-field-title">
			{{ title }}
		</div>
		<slot></slot>
	</div>
</template>

<script>
import { defineComponent } from 'vue'

export default defineComponent({
	name: 'DiscordEmbedField',
	props: {
		title: {
			type: String,
			required: true,
		},
		inline: Boolean,
	},
})
</script>

<style src="@discord-message-components/core/dist/styles/discord-embed-field.css"></style>

// packages/react/src/components/DiscordEmbedField.tsx
import React, { PropsWithChildren, ReactElement } from 'react'
import '@discord-message-components/core/dist/styles/discord-embed-field.css'

export type DiscordEmbedFieldProps = PropsWithChildren<{
	inline?: boolean,
	slot?: string,
	title: string,
}>

export default function DiscordEmbedField({ children, inline, title }: DiscordEmbedFieldProps): ReactElement {
	let classes = 'discord-embed-field'
	if (inline) classes += ' discord-embed-field-inline'

	return (
		<div className={classes}>
			<div className="discord-embed-field-title">{title}</div>
			{children}
		</div>
	)
}
