// packages/vue/src/components/DiscordEmbed.vue
<template>
	<div class="discord-embed">
		<div :style="{ 'background-color': color }" class="discord-embed-left-border"></div>
		<div class="discord-embed-container">
			<div class="discord-embed-content">
				<div>
					<div v-if="author.name" class="discord-embed-author">
						<img v-if="author.icon" :src="author.icon" alt="" class="discord-embed-author-icon" />
						<a v-if="author.url" :href="author.url" target="_blank" rel="noopener noreferrer">
							{{ author.name }}
						</a>
						<span v-else>
							{{ author.name }}
						</span>
					</div>
					<div class="discord-embed-description">
						<slot></slot>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>

<script>
import { computed, defineComponent, toRefs } from 'vue'

export default defineComponent({
	name: 'DiscordEmbed',
	props: {
		authorIcon: String,
		authorName: String,
		authorUrl: String,
		color: String,
	},
	setup(props) {
		const { authorIcon, authorName, authorUrl } = toRefs(props)

		const author = computed(() => ({
			icon: authorIcon?.value,
			name: authorName?.value,
			url: authorUrl?.value,
		}))

		return {
			author,
		}
	},
})
</script>

<style src="@discord-message-components/core/dist/styles/discord-embed.css"></style>

// packages/react/src/components/DiscordEmbed.tsx
import React, { ReactElement, ReactNode } from 'react'
import '@discord-message-components/core/dist/styles/discord-embed.css'

export type DiscordEmbedProps = {
	authorIcon?: string,
	authorName?: string,
	authorUrl?: string,
	children?: ReactNode,
	color?: string,
	slot?: string,
}

export default function DiscordEmbed({ authorIcon, authorName, authorUrl, children, color }: DiscordEmbedProps): ReactElement {
	const content = {
		author: (
			<div className="discord-embed-author">
				{authorIcon
					&& <img src={authorIcon} alt="" className="discord-embed-author-icon" />}
				{authorUrl
					? <a href={authorUrl} target="_blank" rel="noopener noreferrer">{authorName}</a>
					: <span>{authorName}</span>}
			</div>
		),
	}

	return (
		<div className="discord-embed">
			<div style={{ backgroundColor: color }} className="discord-embed-left-border"></div>
			<div className="discord-embed-container">
				<div className="discord-embed-content">
					<div>
						{authorName && content.author}
						<div className="discord-embed-description">
							{children}
						</div>
					</div>
				</div>
			</div>
		</div>
	)
}
