// packages/vue/src/components/DiscordMention.vue
<template>
	<span ref="root" :style="colorStyle" class="discord-mention">
		{{ mentionCharacter }}<slot>{{ defaultContent }}</slot>
	</span>
</template>

<script lang="ts">
import { computed, defineComponent, onBeforeUnmount, onMounted, ref, toRefs } from 'vue'
import { util } from '@discord-message-components/core'

export default defineComponent({
	name: 'DiscordMention',
	props: {
		color: String,
		highlight: Boolean,
		type: {
			type: String,
			'default': 'user',
		},
	},
	setup(props) {
		const { color, type } = toRefs(props)
		const root = ref<HTMLSpanElement>()
		const hovering = ref(false)
		const setHoverColor = () => hovering.value = true
		const resetHoverColor = () => hovering.value = false

		const colors = {
			background: util.parseColorToRgba(color?.value, 0.1),
			hover: util.parseColorToRgba(color?.value, 0.3),
		}

		const colorStyle = computed(() => {
			return color?.value && type.value === 'role'
				? {
					color: color.value,
					'background-color': hovering.value ? colors.hover : colors.background,
				}
				: {}
		})

		onMounted(() => {
			if (color?.value && type?.value === 'role') {
				root?.value?.addEventListener('mouseenter', setHoverColor)
				root?.value?.addEventListener('mouseout', resetHoverColor)
			}
		})

		onBeforeUnmount(() => {
			root?.value?.removeEventListener('mouseenter', setHoverColor)
			root?.value?.removeEventListener('mouseout', resetHoverColor)
		})

		const defaultContent = computed(() => {
			return type.value === 'channel'
				? type.value
				: type.value.charAt(0).toUpperCase() + type.value.slice(1)
		})

		const mentionCharacter = computed(() => type.value === 'channel' ? '#' : '@')

		return {
			root,
			colorStyle,
			defaultContent,
			mentionCharacter,
		}
	},
})
</script>

<style src="@discord-message-components/core/dist/styles/discord-mention.css"></style>

// packages/react/src/components/DiscordMention.tsx
import React, { ReactElement, ReactNode, useEffect, useRef, useState } from 'react'
import { util } from '@discord-message-components/core'
import '@discord-message-components/core/dist/styles/discord-mention.css'

export type DiscordMentionProps = {
	children?: ReactNode,
	color?: string,
	highlight?: boolean,
	type?: string,
}

export default function DiscordMention({ children, color, type = 'user' }: DiscordMentionProps): ReactElement {
	const root = useRef<HTMLSpanElement>(null)
	const [hovering, setHovering] = useState(false)
	const setHoverColor = () => setHovering(true)
	const resetHoverColor = () => setHovering(false)

	const colors = {
		background: util.parseColorToRgba(color, 0.1),
		hover: util.parseColorToRgba(color, 0.3),
	}

	const colorStyle = color && type === 'role'
		? { color, backgroundColor: hovering ? colors.hover : colors.background }
		: {}

	useEffect(() => {
		if (color && type === 'role') {
			root?.current?.addEventListener('mouseenter', setHoverColor)
			root?.current?.addEventListener('mouseout', resetHoverColor)
		}

		return () => {
			root?.current?.removeEventListener('mouseenter', setHoverColor)
			root?.current?.removeEventListener('mouseout', resetHoverColor)
		}
	}, [root, color, type])

	const defaultContent = children || (
		type === 'channel'
			? type
			: type.charAt(0).toUpperCase() + type.slice(1)
	)

	const mentionCharacter = type === 'channel' ? '#' : '@'

	return (
		<span ref={root} style={colorStyle} className="discord-mention">
			{mentionCharacter}{defaultContent}
		</span>
	)
}
