// packages/vue/src/components/DiscordReactions.vue
<template>
	<div class="discord-reactions">
		<slot></slot>
	</div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
	name: 'DiscordReactions',
})
</script>

<style src="@discord-message-components/core/dist/styles/discord-reactions.css"></style>

// packages/react/src/components/DiscordReactions.tsx
import React, { ReactElement } from 'react'
import { PropsWithSlot } from '../util'
import '@discord-message-components/core/dist/styles/discord-reactions.css'

export default function DiscordReactions({ children }: PropsWithSlot): ReactElement {
	return (
		<div className="discord-reactions">
			{children}
		</div>
	)
}
