// packages/vue/src/components/DiscordEmbedFields.vue
<template>
	<div class="discord-embed-fields">
		<slot></slot>
	</div>
</template>

<script>
import { defineComponent } from 'vue'

export default defineComponent({
	name: 'DiscordEmbedFields',
})
</script>

<style src="@discord-message-components/core/dist/styles/discord-embed-fields.css"></style>

// packages/react/src/components/DiscordEmbedFields.tsx
import React, { PropsWithChildren, ReactElement } from 'react'
import '@discord-message-components/core/dist/styles/discord-embed-fields.css'

export type DiscordEmbedFieldsProps = PropsWithChildren<{
	slot?: string,
}>

export default function DiscordEmbedFields({ children }: DiscordEmbedFieldsProps): ReactElement {
	return (
		<div className="discord-embed-fields">
			{children}
		</div>
	)
}
