// packages/vue/src/components/DiscordInteraction.vue
<template>
	<div class="discord-interaction">
		<img class="discord-interaction-author-avatar" :src="user.avatar" alt="" />
		<author-info
			class="discord-interaction-author-info"
			:author="highlight ? `@${user.author}` : user.author"
			:bot="user.bot"
			:role-color="user.roleColor"
		/>
		<span v-if="command" class="discord-interaction-command">
			used
			<span class="discord-interaction-command-name">
				/<slot></slot>
			</span>
		</span>
		<span v-else class="discord-interaction-reply">
			<slot></slot>
			<span v-if="edited" class="discord-interaction-reply-edited">(edited)</span>
		</span>
	</div>
</template>

<script lang="ts">
import { defineComponent, toRefs } from 'vue'
import { util } from '@discord-message-components/core'
import { Profile, resolveOptions } from '../options'
import AuthorInfo from './AuthorInfo.vue'

export default defineComponent({
	components: {
		AuthorInfo,
	},
	props: {
		author: String,
		avatar: String,
		bot: {
			type: Boolean,
			'default': null,
		},
		command: Boolean,
		edited: Boolean,
		ephemeral: Boolean,
		highlight: Boolean,
		profile: String,
		roleColor: String,
	},
	setup(props) {
		const options = resolveOptions()
		const { author, avatar, bot, profile: profileKey, roleColor } = toRefs(props)

		const profile: Profile = !profileKey?.value ? {} : options.profiles?.[profileKey?.value] ?? {}
		const user: Profile = {
			author: !author?.value && profile?.author ? profile.author : author?.value || 'User',
			avatar: util.resolveImage(options.avatars, avatar?.value || profile?.avatar),
			bot: bot.value ?? profile?.bot,
			roleColor: roleColor?.value || profile?.roleColor,
		}

		return {
			user,
		}
	},
})
</script>

<style src="@discord-message-components/core/dist/styles/discord-interaction.css"></style>

// packages/react/src/components/DiscordInteraction.tsx
import React, { ReactElement, useContext } from 'react'
import { util } from '@discord-message-components/core'
import DiscordDefaultOptions, { DiscordMessageOptions, Profile } from '../context/DiscordDefaultOptions'
import DiscordOptionsContext from '../context/DiscordOptionsContext'
import { PropsWithSlot } from '../util'
import AuthorInfo from './AuthorInfo'
import '@discord-message-components/core/dist/styles/discord-interaction.css'

export type DiscordInteractionProps = {
	author?: string
	avatar?: string
	bot?: boolean
	command?: boolean
	edited?: boolean
	ephemeral?: boolean
	highlight?: boolean
	profile?: string
	roleColor?: string
} & PropsWithSlot

export default function DiscordInteraction({
	author,
	avatar,
	bot,
	children,
	command,
	edited,
	highlight,
	profile: profileKey,
	roleColor,
}: DiscordInteractionProps): ReactElement {
	const options: DiscordMessageOptions = useContext(DiscordOptionsContext) ?? DiscordDefaultOptions

	const profile: Profile = options.profiles?.[profileKey] ?? {}
	const user: Profile = {
		author: !author && profile?.author ? profile.author : author || 'User',
		avatar: util.resolveImage(options.avatars, avatar || profile?.avatar),
		bot: bot ?? profile?.bot,
		roleColor: roleColor || profile?.roleColor,
	}

	return (
		<div className="discord-interaction">
			<img className="discord-interaction-author-avatar" src={user.avatar} alt="" />
			<AuthorInfo
				className="discord-interaction-author-info"
				author={highlight ? `@${user.author}` : user.author}
				bot={user.bot}
				roleColor={user.roleColor}
			/>
			{command
				? <span className="discord-interaction-command">
					used{' '}
					<span className="discord-interaction-command-name">
						/{children}
					</span>
				</span>
				: <span className="discord-interaction-reply">
					{children}
					{edited && <span className="discord-interaction-reply-edited">(edited)</span>}
				</span>
			}
		</div>
	)
}
